# Generated by Django 4.0 on 2022-01-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.BooleanField(default=False, help_text='When set indicates is priority. Otherwise it is not a priority item.')),
                ('description', models.CharField(help_text='Brief description of task', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time wi was created. Initial value from system.')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wi.area')),
            ],
        ),
        migrations.DeleteModel(
            name='wi',
        ),
    ]
