# Generated by Django 4.0 on 2022-01-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0002_task_delete_wi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='tasker',
        ),
    ]
