# Generated by Django 4.0 on 2022-01-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0003_rename_task_tasker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasker',
            new_name='wi',
        ),
    ]
