# Generated by Django 4.0 on 2022-01-13 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0006_alter_area_created_alter_area_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 6, 25, 55, 224548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
