# Generated by Django 4.0 on 2022-01-13 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0007_task_status_task_updated_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 6, 28, 1, 679093, tzinfo=utc)),
        ),
    ]
