# Generated by Django 4.0 on 2022-01-13 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0010_task_banana_alter_task_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='banana',
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 13, 7, 37, 28, 650617, tzinfo=utc), null=True),
        ),
    ]
