# Generated by Django 4.0 on 2022-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0011_remove_task_banana_alter_task_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Priority?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
