# Generated by Django 4.0 on 2022-01-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0012_area_updated_alter_area_created_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description2',
            field=models.CharField(default='Jay', max_length=100),
            preserve_default=False,
        ),
    ]
