# Generated by Django 4.0 on 2022-01-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0013_task_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description2',
        ),
    ]
