# Generated by Django 4.0 on 2022-01-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0014_remove_task_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='!'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
    ]
