# Generated by Django 4.0 on 2022-02-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0016_task_createdby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='createdby',
            new_name='created_by',
        ),
    ]
