# Generated by Django 4.0 on 2022-02-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wi', '0017_rename_createdby_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
