# Generated by Django 4.0 on 2022-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0019_domain_area_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='retain_done_tasks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
