# Generated by Django 4.0 on 2022-02-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0021_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='retain_done_tasks',
            new_name='retain_completed_tasks',
        ),
    ]
