# Generated by Django 4.0 on 2022-02-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0022_rename_retain_done_tasks_domain_retain_completed_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='retain_completed_tasks',
            field=models.PositiveIntegerField(default=1, verbose_name='Show done tasks (days)'),
        ),
    ]
