# Generated by Django 4.0 on 2022-03-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wi', '0025_alter_area_options_area_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
